"""changed name column in to string  auth_users table

Revision ID: 5ae63493d914
Revises: d6d3dff15636
Create Date: 2026-03-27 15:06:45.341044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae63493d914'
down_revision: Union[str, Sequence[str], None] = 'd6d3dff15636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'name',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('auth_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('auth_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('auth_users', 'name',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
