"""added 2 column in purchases table

Revision ID: 7eeb7179c607
Revises: 93ead5443133
Create Date: 2026-04-01 18:18:35.303007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eeb7179c607'
down_revision: Union[str, Sequence[str], None] = '93ead5443133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('item_name', sa.String(), nullable=True))
    op.add_column('purchases', sa.Column('item_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'item_category')
    op.drop_column('purchases', 'item_name')
    # ### end Alembic commands ###
