"""rename the password to hased_password

Revision ID: bda320449a4b
Revises: 77c42c771a98
Create Date: 2026-03-27 16:05:02.545830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda320449a4b'
down_revision: Union[str, Sequence[str], None] = '77c42c771a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('auth_users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('auth_users', 'hashed_password')
    # ### end Alembic commands ###
